AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ferry App - Automate Lambda Deployments

Resources:
  GetEnturTimesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_entur_times.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          ENV: production
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /entur-times
            Method: get

  GetStatusMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_status_message.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          ENV: production
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /status-message
            Method: get

Outputs:
  GetEnturTimesApi:
    Description: 'API Gateway endpoint URL for Prod stage for GetEnturTimes'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/entur-times'

  GetStatusMessageApi:
    Description: 'API Gateway endpoint URL for Prod stage for GetStatusMessage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/status-message'
