name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM Application
        run: |
          sam build

      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM --stack-name ferry-app-stack --region us-west-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
